[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Svyatoslav Kening <reveni324@.com>"]
requires-python = ">=3.11"
dependencies = [
    "selenium>=4.32.0",
    "webdriver-manager>=4.0.3",
    "flask>=2.3.0",
]
